Update README.batch.md
liske/needrestart pull request #219
Opened 2021-09-28 08:33 UTC by stdedos

Did you mean: compliant

2022-01-26 02:23 UTC, anarcat approved these changes

2022-01-26 02:45 UTC, anarcat requested changes
actually, now that i reread that sentence, the wording was still not correct.

2022-01-26 02:45 UTC, anarcat commented on README.batch.md
> +nor restart anything. The output format is compliant to the
```suggestion
nor restart anything. The output format is compliant with the
```

2022-01-28 21:43 UTC, merged

2022-01-28 21:43 UTC, liske commented
Thanks!